import test from 'ava'
const { getSignName } = require('./getSignName')

test(       'Aries at     0  º', t => t.assert(getSignName(    0   ) === 'Aries'       ))
test(       'Aries till  29.9º', t => t.assert(getSignName(   29.9 ) === 'Aries'       ))
test(      'Taurus at    30  º', t => t.assert(getSignName(   30   ) === 'Taurus'      ))
test(      'Taurus till  59.9º', t => t.assert(getSignName(   59.9 ) === 'Taurus'      ))
test(      'Gemini at    60  º', t => t.assert(getSignName(   60   ) === 'Gemini'      ))
test(      'Gemini till  89.9º', t => t.assert(getSignName(   89.9 ) === 'Gemini'      ))
test(      'Cancer at    90  º', t => t.assert(getSignName(   90   ) === 'Cancer'      ))
test(      'Cancer till 119.9º', t => t.assert(getSignName(  119.9 ) === 'Cancer'      ))
test(         'Leo at   120  º', t => t.assert(getSignName(  120   ) === 'Leo'         ))
test(         'Leo till 149.9º', t => t.assert(getSignName(  149.9 ) === 'Leo'         ))
test(       'Virgo at   150  º', t => t.assert(getSignName(  150   ) === 'Virgo'       ))
test(       'Virgo till 179.9º', t => t.assert(getSignName(  179.9 ) === 'Virgo'       ))
test(       'Libra at   180  º', t => t.assert(getSignName(  180   ) === 'Libra'       ))
test(       'Libra till 209.9º', t => t.assert(getSignName(  209.9 ) === 'Libra'       ))
test(     'Scorpio at   210  º', t => t.assert(getSignName(  210   ) === 'Scorpio'     ))
test(     'Scorpio till 239.9º', t => t.assert(getSignName(  239.9 ) === 'Scorpio'     ))
test( 'Sagittarius at   240  º', t => t.assert(getSignName(  240   ) === 'Sagittarius' ))
test( 'Sagittarius till 269.9º', t => t.assert(getSignName(  269.9 ) === 'Sagittarius' ))
test(   'Capricorn at   270  º', t => t.assert(getSignName(  270   ) === 'Capricorn'   ))
test(   'Capricorn till 299.9º', t => t.assert(getSignName(  299.9 ) === 'Capricorn'   ))
test(    'Aquarius at   300  º', t => t.assert(getSignName(  300   ) === 'Aquarius'    ))
test(    'Aquarius till 329.9º', t => t.assert(getSignName(  329.9 ) === 'Aquarius'    ))
test(      'Pisces at   330  º', t => t.assert(getSignName(  330   ) === 'Pisces'      ))
test(      'Pisces till 359.9º', t => t.assert(getSignName(  359.9 ) === 'Pisces'      ))
test(       'Aries at   360  º', t => t.assert(getSignName(  360   ) === 'Aries'       ))
